// Copyright 2025 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package net.starlark.truffle;

import com.oracle.truffle.api.TruffleFile;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.TruffleLanguage.Provider;
import java.util.List;

/**
 * Manual provider implementation for TruffleStarlarkLanguage.
 * Normally this would be auto-generated by the Truffle annotation processor.
 */
public final class TruffleStarlarkLanguageProvider implements Provider {

  @Override
  public String getLanguageClassName() {
    return "net.starlark.truffle.TruffleStarlarkLanguage";
  }

  @Override
  public TruffleLanguage<?> create() {
    return new TruffleStarlarkLanguage();
  }

  @Override
  public List<String> getServicesClassNames() {
    return List.of();
  }

  @Override
  public List<TruffleFile.FileTypeDetector> createFileTypeDetectors() {
    return List.of();
  }
}
