// Copyright 2025 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package net.starlark.truffle.nodes;

import com.oracle.truffle.api.dsl.TypeSystem;
import net.starlark.truffle.values.NoneValue;

/**
 * Type system for Starlark values.
 *
 * <p>Defines the primitive and object types that Truffle will specialize for.
 */
@TypeSystem({
    long.class,     // Starlark int (for small values)
    double.class,   // Starlark float
    boolean.class,  // Starlark bool
    String.class,   // Starlark str
    NoneValue.class // Starlark None
})
public class StarlarkTypes {
  // Type system class - methods generated by Truffle DSL
}
